
server:
  port: 8900

spring:
  application:
    name: ribbonandfeigntesting

eureka:
  instance:
    prefer-ip-address: true   #以IP注册为主， 不以主机名注册微服务
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/  
